FROM node:18


RUN apt-get update && apt-get upgrade -y

RUN  apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .


RUN echo package.json 


RUN npm run prep

RUN cat src/public/273175967237441_1707314928948.png


COPY src/public/273175967237441_1707314928948.png dist/public/273175967237441_1707314928948.png


EXPOSE 5000


# CMD ["npm","run","dev"]

CMD ["npm","start"]