FROM node:18


RUN apt-get update && apt-get upgrade -y

RUN  apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .


RUN echo package.json 


RUN npm run prep



EXPOSE 5000


# CMD ["npm","run","dev"]

CMD ["npm","start"]